actions:
  abortActions: []
  emailNotifications: []
  setVariableActions:
  - description: null
    exitCodes: null
    notificationOption: Operation Success
    notifyOnEarlyFinish: false
    notifyOnLateFinish: false
    notifyOnLateStart: false
    notifyOnProjectedLate: false
    status: Success
    sysId: ae3de7974fe744c0a555d21484e7173b
    variableName: ${var_or_condition}
    variableScope: Parent
    variableValue: '1'
  snmpNotifications: []
  systemOperations: []
avgRunTime: 30
avgRunTimeDisplay: 30 Seconds
cpDuration: null
cpDurationUnit: Minutes
customField1:
  label: Requestor Name
  value: null
customField2:
  label: docu link
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.3.0.0
exportTable: ops_task_sleep
firstRun: 2019-11-22 16:42:52 +0100
holdResources: false
lastRun: 2023-03-30 06:40:29 +0200
lastRunTime: 30
lastRunTimeDisplay: 30 Seconds
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxRunTime: 38
maxRunTimeDisplay: 38 Seconds
minRunTime: 30
minRunTimeDisplay: 30 Seconds
name: Sleep 30
notes: []
opswiseGroups:
- KM-Job-as-Code
resPriority: 1
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
runCount: 6962
runTime: 209096
sleepAmount: '30'
sleepDayConstraint: None
sleepDuration: 00:00:00:00
sleepTime: 00:00
sleepType: Seconds
startHeld: false
startHeldReason: null
summary: Sleep for 30 seconds.
sysId: 410d696bc0a801c9017e5dbf756ecbd5
timeZonePref: -- System Default --
type: taskSleep
userEstimatedDuration: null
variables: []
version: 34
virtualResources: []
