actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations:
  - agent: null
    agentCluster: null
    agentClusterVar: null
    agentVar: null
    description: null
    execCommand: Cancel
    execCriteria: Oldest Active Instance
    execId: null
    execLookupOption: Instance Name
    execName: Push-to-Universal_controller from Github Repo
    execWorkflowName: null
    execWorkflowNameCond: Equals
    exitCodes: null
    limit: null
    notificationOption: Operation Failure
    notifyOnEarlyFinish: false
    notifyOnLateFinish: false
    notifyOnLateStart: false
    notifyOnProjectedLate: false
    operation: Run Task Instance Command
    overrideTriggerDateOffset: null
    overrideTriggerDateTime: false
    overrideTriggerTime: 00:00
    status: Finished
    sysId: 48917233e69b45a290185d7ea6b6648f
    task: null
    taskLimitType: Unlimited
    taskVar: null
    trigger: null
    triggerVar: null
    variables: []
    variablesUnresolved: false
    virtualResource: null
    virtualResourceVar: null
  - agent: null
    agentCluster: null
    agentClusterVar: null
    agentVar: null
    description: null
    execCommand: Force Finish/Cancel (Halt)
    execCriteria: Newest Active Instance
    execId: null
    execLookupOption: Instance Name
    execName: Jenkins-Trigger-Main-Branch-Build
    execWorkflowName: null
    execWorkflowNameCond: Equals
    exitCodes: null
    limit: null
    notificationOption: Operation Failure
    notifyOnEarlyFinish: false
    notifyOnLateFinish: false
    notifyOnLateStart: false
    notifyOnProjectedLate: false
    operation: Run Task Instance Command
    overrideTriggerDateOffset: null
    overrideTriggerDateTime: false
    overrideTriggerTime: 00:00
    status: Finished
    sysId: a614c04895c349428d229cb32007da21
    task: null
    taskLimitType: Unlimited
    taskVar: null
    trigger: null
    triggerVar: null
    variables: []
    variablesUnresolved: false
    virtualResource: null
    virtualResourceVar: null
  - agent: null
    agentCluster: null
    agentClusterVar: null
    agentVar: null
    description: slack
    execCommand: Cancel
    execCriteria: Oldest Active Instance
    execId: null
    execLookupOption: Instance Name
    execName: null
    execWorkflowName: null
    execWorkflowNameCond: Equals
    exitCodes: null
    limit: null
    notificationOption: Operation Failure
    notifyOnEarlyFinish: false
    notifyOnLateFinish: false
    notifyOnLateStart: false
    notifyOnProjectedLate: false
    operation: Launch Task
    overrideTriggerDateOffset: null
    overrideTriggerDateTime: false
    overrideTriggerTime: 00:00
    status: Action Required
    sysId: d8d4e8577f034e1681228fdebf436c7a
    task: APPROVAL-NOTIF-SLACK
    taskLimitType: Unlimited
    taskVar: null
    trigger: null
    triggerVar: null
    variables:
    - name: task_status
      value: ${ops_status}
    - name: job_name
      value: ${ops_task_name}:${ops_task_id}
    - name: job_type
      value: ${ops_task_type}
    - name: invoked_by
      value: ${ops_workflow_name}
    - name: exec_user
      value: ${ops_execution_user}
    - name: desc
      value: ${ops_description}:${url}
    variablesUnresolved: false
    virtualResource: null
    virtualResourceVar: null
  - agent: null
    agentCluster: null
    agentClusterVar: null
    agentVar: null
    description: teams
    execCommand: Cancel
    execCriteria: Oldest Active Instance
    execId: null
    execLookupOption: Instance Name
    execName: null
    execWorkflowName: null
    execWorkflowNameCond: Equals
    exitCodes: null
    limit: null
    notificationOption: Operation Failure
    notifyOnEarlyFinish: false
    notifyOnLateFinish: false
    notifyOnLateStart: false
    notifyOnProjectedLate: false
    operation: Launch Task
    overrideTriggerDateOffset: null
    overrideTriggerDateTime: false
    overrideTriggerTime: 00:00
    status: Action Required
    sysId: ead8ce217f5d462791cbe943b6ad5cc7
    task: Approval Notification to Teams
    taskLimitType: Unlimited
    taskVar: null
    trigger: null
    triggerVar: null
    variables:
    - name: task_status
      value: ${ops_status}
    - name: job_name
      value: ${ops_task_name}
    - name: job_type
      value: ${ops_task_type}
    - name: invoked_by
      value: ${ops_workflow_name}
    - name: exec_user
      value: ${ops_execution_user}
    - name: desc
      value: ${ops_description}:${url}
    variablesUnresolved: false
    virtualResource: null
    virtualResourceVar: null
avgRunTime: 16
avgRunTimeDisplay: 16 Seconds
cpDuration: null
cpDurationUnit: Minutes
customField1:
  label: Requestor Name
  value: null
customField2:
  label: docu link
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.3.0.0
exportTable: ops_task_manual
firstRun: 2021-11-15 12:58:51 +0100
holdResources: false
lastRun: 2022-08-24 15:06:50 +0200
lastRunTime: 41
lastRunTimeDisplay: 41 Seconds
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxRunTime: 41
maxRunTimeDisplay: 41 Seconds
minRunTime: 6
minRunTimeDisplay: 6 Seconds
name: Km-Approval-for-Build-in-Jenkins
notes: []
opswiseGroups:
- Karthik Mohan
- KM-Job-as-Code
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
runCount: 6
runTime: 96
startHeld: false
startHeldReason: null
summary: Approve to begin direct main build in jenkins - refer commit
sysId: c990ea8ce7ae4b53954a807b415a8dfe
timeZonePref: -- System Default --
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskManual
userEstimatedDuration: null
variables: []
version: 4
virtualResources: []
