actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
autoCleanup: false
columnName: null
columnOp: '='
columnValue: null
connection: Tomcat81
connectionVar: null
cpDuration: null
cpDurationUnit: Minutes
credentials: SQL local
credentialsVar: null
customField1:
  label: Requestor Name
  value: null
customField2:
  label: docu link
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exitCodes: '0'
exportReleaseLevel: 7.3.0.0
exportTable: ops_task_sql
firstRun: 2020-10-06 10:44:01 +0200
holdResources: false
lastRun: 2020-10-06 10:46:26 +0200
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxRows: null
name: KM SQL TEST
notes: []
opswiseGroups:
- KM-Job-as-Code
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
resultProcessing: Skip Result Processing
retainSysIds: true
retryIndefinitely: false
retryInterval: 60
retryMaximum: 0
retrySuppressFailure: false
runCount: 0
runTime: 0
sqlCommand: "SELECT default_character_set_name FROM information_schema.SCHEMATA \n\
  WHERE schema_name = \"schemaname\";"
startHeld: false
startHeldReason: null
summary: null
sysId: 20127c5a14fa4164aefec3351dc0c8ae
timeZonePref: -- System Default --
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskSql
userEstimatedDuration: null
variables: []
version: 4
virtualResources: []
