actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
agent: Airflow
agentCluster: null
agentClusterVar: null
agentVar: null
authenticatePeer: false
avgRunTime: 0
avgRunTimeDisplay: 0 Seconds
broadcastCluster: null
broadcastClusterVar: null
codepage: -- None --
command: GET
compress: 'NO'
cpDuration: null
cpDurationUnit: Minutes
createop: -- None --
credentials: null
credentialsVar: null
customField1:
  label: Requestor Name
  value: null
customField2:
  label: docu link
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
encrypt: 'NO'
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exitCodeOutput: null
exitCodeProcessing: Success Exitcode Range
exitCodeText: null
exitCodes: '0'
exportReleaseLevel: 7.3.0.0
exportTable: ops_task_ftp
firstRun: 2022-11-17 18:47:32 +0100
formOrScript: Script
format: Text
ftpSubcommands: null
holdResources: false
jobcard: null
lastRun: 2022-11-17 18:48:31 +0100
lastRunTime: 0
lastRunTimeDisplay: 0 Seconds
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
localFilename: '"D:\karthik\sales data\sales-report\sub1\sub2\*"'
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxRunTime: 0
maxRunTimeDisplay: 0 Seconds
minRunTime: 0
minRunTimeDisplay: 0 Seconds
move: false
name: KM-UDM-Update-Variable
nft: false
notes: []
opswiseGroups:
- KM-Job-as-Code
outputType: STDOUT
primaryBroker: null
primaryBrokerChoice: Agent
primaryBrokerRef: Frankfurt
primaryCluster: null
primaryClusterRef: null
primaryCredVar: null
primaryCredentials: Frankfurt_UDM
primaryFilesys: -- None --
primaryOpenOptions: null
remoteCredVar: null
remoteCredentials: null
remoteFilename: /home/karthik/
remoteServer: null
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
retryExitCodes: null
retryIndefinitely: false
retryInterval: 60
retryMaximum: 0
retrySuppressFailure: false
runCount: 2
runTime: 0
runtimeDir: null
script: km-udm-update-variable
secondaryBroker: null
secondaryBrokerChoice: Agent
secondaryBrokerRef: Airflow
secondaryCluster: null
secondaryClusterRef: null
secondaryCredVar: null
secondaryCredentials: airflow-root
secondaryFilesys: -- None --
secondaryOpenOptions: null
serverType: UDM
showProgress: false
startHeld: false
startHeldReason: null
summary: null
sysId: 8c5354c3b8ed4a6089aa1fbcab13da09
timeZonePref: -- System Default --
transferDirection: PUT
transferMode: Passive
trimSpace: false
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskFtp
udmOperation: Copy
udmOptions: null
useRegex: false
userEstimatedDuration: null
variables: []
verifyHostName: false
version: 5
virtualResources: []
