actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
autoCleanup: false
avgRunTime: 3
avgRunTimeDisplay: 3 Seconds
cpDuration: null
cpDurationUnit: Minutes
credentials: null
credentialsVar: null
customField1:
  label: Requestor Name
  value: null
customField2:
  label: docu link
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.3.0.0
exportTable: ops_task_web_service
firstRun: 2022-06-12 13:25:40 +0200
formData: []
holdResources: false
httpAuth: None
httpHeaders: []
httpMethod: GET
httpPayloadType: Raw
httpVersion: '1.1'
insecure: false
lastRun: 2023-02-06 16:29:13 +0100
lastRunTime: 4
lastRunTimeDisplay: 4 Seconds
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxRunTime: 4
maxRunTimeDisplay: 4 Seconds
mimeType: null
minRunTime: 0
minRunTimeDisplay: 0 Seconds
name: KM-Azure-Function-http-trigger
notes: []
opswiseGroups:
- KM-Job-as-Code
outputConditionOperator: '='
outputConditionStrategy: Match Any
outputConditionValue: null
outputPathExpression: null
outputType: Text
payload: null
payloadScript: null
payloadSource: Form
protocol: HTTP(S)/REST
resPriority: 10
resolveNameImmediately: false
responseProcessingType: Default Success Status Code Range
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
retryIndefinitely: false
retryInterval: 60
retryMaximum: 0
retrySuppressFailure: false
runCount: 11
runTime: 28
soapAction: null
soapPayloadType: Body
soapResponseOutput: Body/First Element
soapVersion: '1.2'
startHeld: false
startHeldReason: null
statusCodeRange: null
summary: Invoke HTTP trigger of an Azure Function
sysId: 54fcdd3c434641b39ea23a24c2774940
timeZonePref: -- System Default --
timeout: null
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskWebService
url: https://uacfunction2.azurewebsites.net/api/HttpTrigger1
urlParameters:
- name: code
  value: RJQydFAseij7PSsVlMgEgUHPEUjN3wmH5v6o3qdIvgzlAzFu98YX7w==
userEstimatedDuration: null
variables: []
version: 5
virtualResources: []
