actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
cpDuration: null
cpDurationUnit: Minutes
credentials: null
credentialsVar: null
customField1:
  label: Requestor Name
  value: null
customField2:
  label: docu link
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.3.0.0
exportTable: ops_task_recurring
firstRun: ''
holdResources: false
indefiniteRecurrences: true
intervalEndDayConstraint: None
intervalEndTime: null
intervalStartDayConstraint: None
intervalStartTime: null
lastRun: ''
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
name: KM-Recurring-Task
notes: []
numberOfRecurrences: null
opswiseGroups:
- KM-Job-as-Code
overrideVariables: []
rdExcludeBackupRt: false
recurrenceInterval: '5'
recurrenceIntervalUnit: Minutes
recurrenceTimeList: []
recurrenceType: Interval
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
retentionDurationPurgeRt: false
retentionDurationRt: 1
retentionDurationUnitRt: Days
retryIndefinitely: false
retryInterval: 60
retryMaximum: 0
retrySuppressFailure: false
runCount: 0
runTime: 0
skipCondition: None
startHeld: false
startHeldReason: null
summary: null
sysId: d14295c1b97f427c8fdf5b02c92ea486
targetTask: KM-DEMO-ANGILIAN-WATERS
targetTaskMonitorCondition: None
targetTaskStatusText: null
timeWindow: false
timeZonePref: -- System Default --
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskRecurring
userEstimatedDuration: null
variables: []
version: 2
virtualResources: []
