actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
cpDuration: null
cpDurationUnit: Minutes
customField1:
  label: Requestor Name
  value: null
customField2:
  label: docu link
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
eventTemplate:
  label: github
  value: kmgithubevent
eventType: Global
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
expirationAction: Failed
exportReleaseLevel: 7.3.0.0
exportTable: ops_task_universal_monitor
filter:
  criteria:
  - name: payload
    operator: CONTAINS
    type: criterion
    value: KM-JaC-Test
  - name: x_github_event
    operator: CONTAINS
    type: criterion
    value: push
  - name: landscape
    operator: CONTAINS
    type: criterion
    value: km
  - name: payload
    operator: DOES_NOT_CONTAIN
    type: criterion
    value: Push from UAC
  - name: payload
    operator: CONTAINS
    type: criterion
    value: refs/heads/main
  logicalOperator: And
firstRun: ''
holdResources: false
lastRun: ''
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
name: Github Event Monitor Test
notes: []
opswiseGroups:
- Karthik Mohan
- KM-Job-as-Code
relativeTimeFrom: 00:00
relativeTimeTo: null
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
runCount: 0
runTime: 0
startHeld: false
startHeldReason: null
summary: JaC event Monitor for Github Test repo
sysId: 7bb05e6a1fd74e75a26d328ea229188d
taskUniversal: null
taskUniversalVariables: []
template: null
templateEventTemplate: null
timeScope: -- None --
timeZonePref: -- System Default --
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskUniversalMonitor
userEstimatedDuration: null
variables: []
version: 3
virtualResources: []
